### ISSUE TITLE
HapiJS/Hoek vulnerability issue

### ISSUE THREAD

**Issue by darielnoel** [EveryMundo/emDataStandards#12]
I was trying to find the solution but I found this out:

![image](https://user-images.githubusercontent.com/3312990/40747533-92d6bd78-642b-11e8-9f81-34e9d16e3a99.png)

https://github.com/hapijs/hoek/issues/247

@danielsan , @neilgoldman Do you have any idea?

**Comment by danielsan** [comment]
Yep,

*npm install -g npm@latest*

then

*npm audit fix*

let me know how it goes

**Comment by BigDataKatha** [comment]
Find dependency: npm i boom@latest
Update version: npm update
