### ISSUE TITLE
we should rename the **database** field

### ISSUE THREAD

**Issue by danielsan** [EveryMundo/emDataStandards#18]
The **database** field has some issues.

The folowing fields are automatically created by datacore at the root level

- **_id**
- **__v**
- **__createdAt**

This means those fields are not created by developers and that they are not going to be under the **database** field.

After removing those fields, the ones that stay there don't have much todo with the term _database_.

After having a conversation with @neilgoldman and @yartiles we concluded that a better name for that field would be **metadata** and the changes would be like you can see below:

**FROM**
```json
  "database": {
    "@type": "Database",
    "_id": "14961881240552180.141840260",
    "version": "2.1.0",
    "__createdat": "2017-11-28 15:46:02",
    "__v": 1,    
    "trackingId": "RTJFKFRA2017073120170824$0_123456KARIN",
    "schemaVersion": 1
  }
```

**TO**
```json
  "metadata": {
    "@type": "Metadata",
    "app": {
      "name": "Farenet | GoogleITA UA Client",
      "version": "2.1.0",
      "datasource": "UA IBE | Google ITA API Stating",
    },
    "trackingId": "RTJFKFRA2017073120170824$0_123456KARIN",
    "schemaVersion": "0.0.1"
  }
```

**Comment by yartiles** [comment]
With this "metadata" field I think we can remove the field "reservationStatus" from the Farenet document. This field is used in Farenet to specified where the data was collected, that is the "datasource" of the document. It will look like this: 
"metadata": {
    "@type": "Metadata",
    "app": {
      "name": "Farenet | GoogleITA UA Client",
      "version": "2.1.0",
      "datasource": "IBE_FLIGHT_SELECTION",
    },
    "trackingId": "RTJFKFRA2017073120170824$0_123456KARIN",
    "schemaVersion": "0.0.1"
  }

**Comment by BigDataKatha** [comment]
If @neilgoldman and @danielsan agree with the latest suggestion, I can make the changes.

**Comment by neilgoldman** [comment]
I agree with both suggestions

**Comment by BigDataKatha** [comment]
Updated database object: https://github.com/EveryMundo/emDataStandards/blob/master/types/database.schema.json

New metadata object: https://github.com/EveryMundo/emDataStandards/blob/master/types/metadata.schema.json
