### ISSUE TITLE
Missin main airline field in the Farenet Document

### ISSUE THREAD

**Issue by danielsan** [EveryMundo/emDataStandards#3]
We see the airlines but only in the legs but the whole document should belong to an Airline

**Comment by neilgoldman305** [comment]
>  However, what if we add autoRental or hotel to the fareNet document?

Good point. I think it makes sense under the "flightReservation" object.

Looking at that object though, does "boardingGroup" belong? Is it always consistent across all flights in a trip? If so I'll be quiet, if not I'll move that to a different issue.

**Comment by BigDataKatha** [comment]
This has been fixed by adding the following field to the journey property:
```json
   "airline": {
      "@type": "Airline",
      "name": "EveryMundo",
      "iataCode": "EM"
     }
```
