### ISSUE TITLE
Can you guys please see if it is possible the creation of a logo property inside the Airline Entity?

### ISSUE THREAD

**Issue by darielnoel** [EveryMundo/emDataStandards#35]
**Current**

https://everymundo.github.io/emDataStandards/documentation/build/#airline

![image](https://user-images.githubusercontent.com/3312990/52170695-14eb2380-271d-11e9-9a5b-9ddc90a26288.png)

**Eg: **
```json
{
  "iataCode": "EM",
  "logo": "https://em-airline.com/cool-logo.png" 
}
```

**Comment by BigDataKatha** [comment]
Thank you for your contribution, @darielnoel ! A logo property has been added.
