### ISSUE TITLE
rename dapartureDay and returnDay fields

### ISSUE THREAD

**Issue by danielsan** [EveryMundo/emDataStandards#4]
https://github.com/EveryMundo/emDataStandards/blob/38baf6bb8afa659dff41405dc04dfdc0f27b2576/types/fareNet3.0.example.json#L454

field **departureDay** should be renamed to "departureWeekDay"
field **returnDay** should be renamed to "returnWeekDay"

The value should a three letter code:
SUN, MON, TUE, WED, THU, FRI, SAT

**Comment by BigDataKatha** [comment]
@danielsan - Changed under emDataStandards/types/journey.example.json because the field mentioned was removed under fareNet3.0
