### ISSUE TITLE
Schema For airline site

### ISSUE THREAD

**Issue by ashokbhamla** [EveryMundo/emDataStandards#47]
Hey Members 
I have 2 site using multiple of Schema 
Can you please review  using multiple schema is okay or not.
1. [https://delta-airlines-reservation.com](https://delta-airlines-reservation.com)
2. [https://www.airlinesmap.com.com/delta-airlines](https://www.airlinesmap.com.com/delta-airlines)

**Comment by BigDataKatha** [comment]
Hi @ashokbhamla - you may want to check out the documentation of schema.org for more information on the use of schemas: https://schema.org/docs/gs.html

This repo is mainly concerned with developing data standards.
