### ISSUE TITLE
We should not add timezone to the dates

### ISSUE THREAD

**Issue by danielsan** [EveryMundo/emDataStandards#5]
https://github.com/EveryMundo/emDataStandards/blob/38baf6bb8afa659dff41405dc04dfdc0f27b2576/types/fareNet3.0.example.json#L12

All the dates should be GMT (UTC 0) by default.

**Comment by neilgoldman305** [comment]
I agree about storing dates as UTC 0.

Do you think there'd be any value in storing this in a separate field at a higher-level in the document, like "journey.customerTimezone" or something?

**Comment by BigDataKatha** [comment]
Agreed to remove -5:00 (time zone identifier) in bookingTime variable because all data is stored in UTC 0. For departure time variable, we will copy IBE data as is (no conversion and no timeZone variable)

**Comment by BigDataKatha** [comment]
Change has been committed.
